// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emuidhlpdcdedxjljusv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdWlkaGxwZGNkZWR4amxqdXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTc3NjEsImV4cCI6MjA2OTIzMzc2MX0.edsFb4ADhaE4QsmcC322CMozLyLEb3rV980cWPC_Af4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});