// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snyouxqczdwyqjxwkygy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNueW91eHFjemR3eXFqeHdreWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjQxMDIsImV4cCI6MjA3MTc0MDEwMn0.ThcMXaIDlBS6t-we4g8sAuEnKrxhaykARa1TxbG44xU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});